In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data =pd.read_csv('Insurance_dataset.csv')
data.head()

Age  Affordibility  Bought_Insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
data.shape

(28, 3)

# Train and Testing

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
features=data.drop(columns=['Bought_Insurance'])
features

Age  Affordibility
0    22              1
1    25              0
2    47              1
3    52              0
4    46              1
5    56              1
6    55              0
7    60              0
8    62              1
9    61              1
10   18              1
11   28              1
12   27              0
13   29              0
14   49              1
15   55              1
16   25              0
17   58              1
18   19              0
19   18              1
20   21              1
21   26              0
22   40              1
23   45              1
24   50              1
25   54              1
26   23              1
27   46              1

In [6]:
target=data[['Bought_Insurance']]
target


Bought_Insurance
0                  0
1                  0
2                  1
3                  0
4                  1
5                  1
6                  0
7                  1
8                  1
9                  1
10                 0
11                 0
12                 0
13                 0
14                 1
15                 1
16                 1
17                 1
18                 0
19                 0
20                 0
21                 0
22                 1
23                 1
24                 1
25                 1
26                 0
27                 0

In [7]:
xtrain,xtest,ytrain,ytest=train_test_split(features,target,test_size=0.2,random_state=42)

In [8]:
xtrain.shape

(22, 2)

In [9]:
ytest

Bought_Insurance
9                  1
25                 1
8                  1
21                 0
0                  0
12                 0

# data scaling
If we do scaling, machine learning algorithm do perform better

In [10]:
xtrain_scaled=xtrain.copy()
xtrain_scaled['Age']=xtrain_scaled['Age']/100

In [11]:
xtest_scaled=xtest.copy()
xtest_scaled['Age']=xtest_scaled['Age']/100

In [12]:
xtrain_scaled

Age  Affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1
1   0.25              0
4   0.46              1
5   0.56              1
2   0.47              1
16  0.25              0
23  0.45              1
3   0.52              0
26  0.23              1
24  0.50              1
18  0.19              0
27  0.46              1
20  0.21              1
7   0.60              0
10  0.18              1
14  0.49              1
19  0.18              1
6   0.55              0

In [13]:
xtest_scaled

Age  Affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

# Creating keras model 

In [14]:
from tensorflow import keras 

In [15]:
# here creating a sequential model with only one layer
model=keras.Sequential([ 
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros') # here 1 = output shape/nouron
])                                                                                                                 # input_shape=(2,) refere input shape/nouron   
                                                                                                                # kernel_initializer='ones' refers weight value which is one according to lecture  
                                                                                                                # bias_initializer='zeros' refers bias value which is zeros        ,,  

# Compiling model

In [16]:
model.compile(optimizer='adam',
              loss='binary_crossentropy', # using binary_crossentropy because outputs are binary
              metrics=['accuracy']
)

model.fit(xtrain_scaled,ytrain,epochs=400) # model.fit run the training means trian the model
                                            # epochs=5000 return best accuracy

Epoch 1/400
1/1 [==============================] - 2s 2s/step - loss: 0.7428 - accuracy: 0.5000
Epoch 2/400
1/1 [==============================] - 0s 9ms/step - loss: 0.7424 - accuracy: 0.5000
Epoch 3/400
1/1 [==============================] - 0s 13ms/step - loss: 0.7420 - accuracy: 0.5000
Epoch 4/400
1/1 [==============================] - 0s 10ms/step - loss: 0.7416 - accuracy: 0.5000
Epoch 5/400
1/1 [==============================] - 0s 11ms/step - loss: 0.7411 - accuracy: 0.5000
Epoch 6/400
1/1 [==============================] - 0s 9ms/step - loss: 0.7407 - accuracy: 0.5000
Epoch 7/400
1/1 [==============================] - 0s 7ms/step - loss: 0.7403 - accuracy: 0.5000
Epoch 8/400
1/1 [==============================] - 0s 11ms/step - loss: 0.7399 - accuracy: 0.5000
Epoch 9/400
1/1 [==============================] - 0s 10ms/step - loss: 0.7395 - accuracy: 0.5000
Epoch 10/400
1/1 [==============================] - 0s 10ms/step - loss: 0.7390 - accuracy: 0.5000
Epoch 11/400
1/1 [======

# Model evaluation

In [17]:
model.evaluate(xtest_scaled,ytest)

1/1 [==============================] - 1s 675ms/step - loss: 0.5595 - accuracy: 0.8333


[0.5594589710235596, 0.8333333134651184]

# prediction 

In [18]:
xtest_scaled

Age  Affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

In [19]:
ytest

Bought_Insurance
9                  1
25                 1
8                  1
21                 0
0                  0
12                 0

In [20]:
model.predict(xtest_scaled) # less than .5 means a person didn't accept an insurance

1/1 [==============================] - 0s 185ms/step


array([[0.6940154 ],
       [0.6826885 ],
       [0.695615  ],
       [0.46573696],
       [0.6282608 ],
       [0.46761444]], dtype=float32)

In [21]:
coef, intercept=model.get_weights() #return final weight and bias value
coef, intercept

(array([[0.75435  ],
        [0.6922041]], dtype=float32),
 array([-0.33339837], dtype=float32))

In [22]:
coef # weight value

array([[0.75435  ],
       [0.6922041]], dtype=float32)

In [23]:
intercept #bias value

array([-0.33339837], dtype=float32)

# impelment same method from scraching python 
[without tensorflow] 

In [24]:
import math

In [25]:
def simgoid(x):
    return 1/(1+math.exp(-x))
simgoid(18)

0.9999999847700205

In [26]:
def prediction_function(Age,Affordibility):
    weighted_sum=coef[0]*Age+coef[1]*Affordibility+intercept
    return simgoid(weighted_sum)

In [27]:
prediction_function(0.61,1) #this function predicts only for row of xtest_scaled

0.6940153701788261

In [28]:
prediction_function(.54,1) # this is for secoend row

0.6826885060473599

In [29]:
def log_loss(y_true,y_predicted): # log losss calcuation
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [30]:
def simgoid_numpy(x):
    return 1/(1+np.exp(-x))
simgoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [31]:
def gradient_descent(Age,Affordability,y_true,epochs, loss_thresold):
    w1=w2=1
    bias=0
    rate=0.5
    n=len(Age)
    for i in range(epochs):
        weighted_sum=w1*Age+w2*Affordability+bias
        y_predicted=simgoid_numpy(weighted_sum)
        loss=log_loss(y_true,y_predicted)
        w1d=(1/n)*np.dot(np.transpose(Age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(Affordability),(y_predicted-y_true))
        bias_d=np.mean(y_predicted-y_true)
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        print(f"Epoch: {i},  w1: {w1}, w2: {w2}, bias: {bias}, loss{loss}")
        if loss<=loss_thresold:
            break

    return w1,w2,bias
 

In [ ]:
gradient_descent(xtrain_scaled['Age'],xtest_scaled['Affordibility'],ytrain,100,0.4631)

In [ ]:
data.columns