In [1]:
import math 

# | Sigmoid Function

In [2]:


def sigmoid(x):
    return 1/(1+math.exp(-x))

In [3]:
sigmoid(100)

1.0

In [4]:
sigmoid(1)

0.7310585786300049

In [5]:
sigmoid(-56)

4.780892883885469e-25

In [6]:
sigmoid(-1)

0.2689414213699951

In [7]:
sigmoid(0)

0.5

In [8]:
sigmoid(.5)

0.6224593312018546

# | tenh Function

In [9]:
def tenh(x):
    return (math.exp(x)-math.exp(-x)) / (math.exp(x)+math.exp(-x))

In [10]:
tenh(-1)

-0.7615941559557649

In [11]:
tenh(1)

0.7615941559557649

In [12]:
tenh(-56)

-1.0

In [13]:
tenh(56)

1.0

# | ReLU Function

In [14]:
def relu(x):
    return max(0,x)

In [15]:
relu(-7) # any negative value return zero

0

In [16]:
relu(-56)

0

In [17]:
relu(0)

0

In [18]:
relu(1)

1

In [19]:
relu(76)

76

# | Leaky ReLU Function

In [20]:
def leaky_relu(x):
    return max(0.1*x,x)

In [21]:
leaky_relu(1)

1

In [22]:
leaky_relu(-1)

-0.1

In [23]:
leaky_relu(-100)

-10.0

In [24]:
leaky_relu(100)

100

# matrix

Numpy Broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [2]:
import numpy as np

| Matrix Subtraction

In [3]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit=revenue-expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

| Matrix Multiplication

In [5]:
price_per_unit=np.array([1000,400,1200])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [6]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [7]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [8]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [9]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

# Loss and cost function

| Mean Absolute error

In [20]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.3,0.7,1,0,0.5])

In [25]:
def mae(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        #print(yt,'  ',yp)
        total_error+=abs(yt-yp)
    print('total error:',total_error)
    mae=total_error/len(y_true)
    print('MAE: ',mae)


In [26]:
mae(y_true,y_predicted)

total error: 2.5
MAE:  0.5


In [48]:
# or
# MAE
np.mean(a=np.abs(y_true-y_predicted))

0.5

| Mean squared error

In [39]:
a=np.abs(y_true-y_predicted)
a

array([0.7, 0.3, 1. , 0. , 0.5])

In [49]:
np.mean(np.square(a))


0.366

| log loss or binary cross entropy

In [58]:
np.log([0.000000000000001])

array([-34.53877639])

In [71]:
eplison=1e-15

In [63]:
y_predicted

array([1, 1, 0, 0, 1])

In [73]:
y_predicted_new=[max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [74]:
y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [80]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [82]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844